name: Daily Holiday Check

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: pip install requests

      - name: Run bot
        run: python holiday_bot.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_URL_CREATETTA: ${{ secrets.SLACK_WEBHOOK_URL_CREATETTA }}
          CALENDARIFIC_API_KEY: ${{ secrets.CALENDARIFIC_API_KEY }}
